application: bubbly-fuze-341
version: webcrawler-20140118-01
runtime: go
api_version: go1

default_expiration: "1m"

handlers:
- url: /(.*\.html)
  static_files: static/\1
  upload: static/(.*\.html)

- url: /_ah/stats/.*
  script: _go_app

- url: /.*
  script: _go_app
